name: 'Setup fpm'
description: 'Setup the Fortran Package Manager for use in Github actions CI'
branding:
  color: purple
  icon: package
inputs:
  github-token:
    description: 'API token needed to fetch latest fpm version'
    required: false
    default: 'none'
  fpm-version:
    description: 'The tag of an fpm release'
    required: false
    default: 'v0.11.0'
  fpm-repository:
    description: 'Github repository (url) serving fpm releases'
    required: false
    default: 'https://github.com/fortran-lang/fpm'
runs:
  using: 'node20'
  main: 'index.js'
