on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fpm-version: ['v0.1.0','v0.1.1','latest']
        node-version: ['20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: fpm-setup
        uses: ./ # Uses action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: test fpm
        run: fpm --help
